apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-web-app
  labels:
    app: go-web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-web-app
  template:
    metadata: 
      labels:
        app: go-web-app  # ✅ match this with selector
    spec:
      containers:
      - name: go-web-app
        image: arka1206/go-web-app:v1
        ports:
        - containerPort: 8080